### ISSUE TITLE
Fix zeros in x-axis of Figure 6

### ISSUE THREAD

**Issue by joseph-s-shapiro** [joseph-s-shapiro/erc#1]
Remove the "0" from the x-axis of panels A and B of figure 6. I think that's what's causing the problem in Panel A, and it looks strange in Panel B to have the 0 floating in the bottom-left of the graph. [transferred from email, let's use github for issues now that we're all on it]

@reed-walker

**Comment by rayhkim** [comment]
@joseph-s-shapiro The updated graphs with 0s removed are in results/figures/f4. You can transfer them over to the corresponding folder in the current draft to see them on the paper.
