### ISSUE TITLE
Minor appendix table formatting changes

### ISSUE THREAD

**Issue by joseph-s-shapiro** [joseph-s-shapiro/erc#5]
AT1: please fix table notes so they are directly below the table like the other tables have (currently they are floating off to the left)

AT4: please fill the blanks with long dashes, like we have in T4

AT6: column numbers should be (1) (2) (3). (Currently there's no (3), and is a (4).) Also, can the three columns have roughly similar width? Currently the third column is much wider.

@reed-walker

**Comment by rayhkim** [comment]
I made the fixes—let me know if everything looks good.

**Comment by joseph-s-shapiro** [comment]
Thanks for fixing these. Only remaining issue is that the appendix page ordering is figure/table/figure/table. Can you order it like the submitted version had, where the page ordering has all appendis tables and then after that all appendix figures?
https://www.joseph-s-shapiro.com/research/IsAirPollutionRegulationTooStringent_maintext.pdf

**Comment by rayhkim** [comment]
Done. Let me know if everything looks good.

**Comment by joseph-s-shapiro** [comment]
Summary: the current latex and PDF addresses all the above issues.
